services:
  ubuntu-learning-lab:
    build: .
    container_name: basic-ubuntu-lab
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./workspace:/workspace
    ports:
      - "3000:3000"